// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmichorizon/qwoyn/aquifer/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	Maintainer             string                                 `protobuf:"bytes,1,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	DepositToken           string                                 `protobuf:"bytes,2,opt,name=deposit_token,json=depositToken,proto3" json:"deposit_token,omitempty"`
	AllocationToken        string                                 `protobuf:"bytes,3,opt,name=allocation_token,json=allocationToken,proto3" json:"allocation_token,omitempty"`
	VestingDuration        uint64                                 `protobuf:"varint,4,opt,name=vesting_duration,json=vestingDuration,proto3" json:"vesting_duration,omitempty"`
	DepositEndTime         uint64                                 `protobuf:"varint,5,opt,name=deposit_end_time,json=depositEndTime,proto3" json:"deposit_end_time,omitempty"`
	InitLiquidityPrice     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=init_liquidity_price,json=initLiquidityPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"init_liquidity_price"`
	Discount               github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=discount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"discount"`
	LiquidityBootstrapping bool                                   `protobuf:"varint,8,opt,name=liquidity_bootstrapping,json=liquidityBootstrapping,proto3" json:"liquidity_bootstrapping,omitempty"`
	LiquidityBootstrapped  bool                                   `protobuf:"varint,9,opt,name=liquidity_bootstrapped,json=liquidityBootstrapped,proto3" json:"liquidity_bootstrapped,omitempty"`
	IcaConnectionId        string                                 `protobuf:"bytes,10,opt,name=ica_connection_id,json=icaConnectionId,proto3" json:"ica_connection_id,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_456a9e6e8c00aeb9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaintainer() string {
	if m != nil {
		return m.Maintainer
	}
	return ""
}

func (m *Params) GetDepositToken() string {
	if m != nil {
		return m.DepositToken
	}
	return ""
}

func (m *Params) GetAllocationToken() string {
	if m != nil {
		return m.AllocationToken
	}
	return ""
}

func (m *Params) GetVestingDuration() uint64 {
	if m != nil {
		return m.VestingDuration
	}
	return 0
}

func (m *Params) GetDepositEndTime() uint64 {
	if m != nil {
		return m.DepositEndTime
	}
	return 0
}

func (m *Params) GetLiquidityBootstrapping() bool {
	if m != nil {
		return m.LiquidityBootstrapping
	}
	return false
}

func (m *Params) GetLiquidityBootstrapped() bool {
	if m != nil {
		return m.LiquidityBootstrapped
	}
	return false
}

func (m *Params) GetIcaConnectionId() string {
	if m != nil {
		return m.IcaConnectionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmichorizon.qwoyn.aquifer.Params")
}

func init() {
	proto.RegisterFile("cosmichorizon/qwoyn/aquifer/params.proto", fileDescriptor_456a9e6e8c00aeb9)
}

var fileDescriptor_456a9e6e8c00aeb9 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x13, 0x8d, 0xeb, 0x76, 0x50, 0x5b, 0x87, 0x5a, 0x07, 0x85, 0xec, 0xa2, 0x20, 0x51,
	0x68, 0x72, 0x10, 0x11, 0x3c, 0xae, 0xf5, 0x50, 0xf1, 0x50, 0x42, 0x4f, 0x5e, 0xe2, 0xec, 0xcc,
	0x98, 0x3e, 0xba, 0x99, 0x97, 0x9d, 0x99, 0xa8, 0xeb, 0xa7, 0xf0, 0xe8, 0x45, 0xf0, 0xe3, 0xf4,
	0xd8, 0xa3, 0x78, 0x28, 0xb2, 0xfb, 0x45, 0x24, 0xd3, 0x34, 0x6d, 0xa5, 0x27, 0x4f, 0x09, 0xff,
	0xf7, 0xfb, 0xff, 0xf3, 0x5e, 0xde, 0x23, 0x89, 0x40, 0x5b, 0x81, 0x38, 0x40, 0x03, 0x5f, 0x51,
	0x67, 0xf3, 0xcf, 0xb8, 0xd0, 0x19, 0x9f, 0x37, 0xf0, 0x51, 0x99, 0xac, 0xe6, 0x86, 0x57, 0x36,
	0xad, 0x0d, 0x3a, 0xa4, 0x0f, 0x2f, 0x91, 0xa9, 0x27, 0xd3, 0x8e, 0x7c, 0xb0, 0x59, 0x62, 0x89,
	0x9e, 0xcb, 0xda, 0xb7, 0x53, 0xcb, 0xa3, 0x1f, 0x11, 0x19, 0xec, 0xf9, 0x0c, 0x1a, 0x13, 0x52,
	0x71, 0xd0, 0x8e, 0x83, 0x56, 0x86, 0x85, 0xe3, 0x30, 0x59, 0xcb, 0x2f, 0x28, 0xf4, 0x31, 0xb9,
	0x2d, 0x55, 0x8d, 0x16, 0x5c, 0xe1, 0xf0, 0x50, 0x69, 0x76, 0xcd, 0x23, 0xb7, 0x3a, 0x71, 0xbf,
	0xd5, 0xe8, 0x53, 0xb2, 0xc1, 0x67, 0x33, 0x14, 0xdc, 0x01, 0xea, 0x8e, 0xbb, 0xee, 0xb9, 0xf5,
	0x73, 0xbd, 0x47, 0x3f, 0x29, 0xeb, 0x40, 0x97, 0x85, 0x6c, 0x8c, 0x2f, 0xb0, 0x68, 0x1c, 0x26,
	0x51, 0xbe, 0xde, 0xe9, 0x3b, 0x9d, 0x4c, 0x13, 0xb2, 0x71, 0xf6, 0x69, 0xa5, 0x65, 0xe1, 0xa0,
	0x52, 0xec, 0x86, 0x47, 0xef, 0x74, 0xfa, 0x1b, 0x2d, 0xf7, 0xa1, 0x52, 0xf4, 0x03, 0xd9, 0x04,
	0x0d, 0xae, 0x98, 0xc1, 0xbc, 0x01, 0x09, 0x6e, 0x51, 0xd4, 0x06, 0x84, 0x62, 0x83, 0xb6, 0x87,
	0x49, 0x7a, 0x74, 0x32, 0x0a, 0x7e, 0x9f, 0x8c, 0x9e, 0x94, 0xe0, 0x0e, 0x9a, 0x69, 0x2a, 0xb0,
	0xca, 0xda, 0x7f, 0x86, 0xb6, 0x7b, 0x6c, 0x5b, 0x79, 0x98, 0xb9, 0x45, 0xad, 0x6c, 0xba, 0xa3,
	0x44, 0x4e, 0xdb, 0xac, 0x77, 0x67, 0x51, 0x7b, 0x6d, 0x12, 0x7d, 0x4b, 0x86, 0x12, 0xac, 0xc0,
	0x46, 0x3b, 0x76, 0xf3, 0xbf, 0x52, 0x7b, 0x3f, 0x7d, 0x49, 0xee, 0x9f, 0x37, 0x3a, 0x45, 0x74,
	0xd6, 0x19, 0x5e, 0xd7, 0xa0, 0x4b, 0x36, 0x1c, 0x87, 0xc9, 0x30, 0xdf, 0xea, 0xcb, 0x93, 0x8b,
	0x55, 0xfa, 0x82, 0x6c, 0x5d, 0x65, 0x54, 0x92, 0xad, 0x79, 0xdf, 0xbd, 0x2b, 0x7c, 0x4a, 0xd2,
	0x67, 0xe4, 0x2e, 0x08, 0x5e, 0x08, 0xd4, 0x5a, 0x09, 0xbf, 0x21, 0x90, 0x8c, 0x9c, 0xae, 0x07,
	0x04, 0x7f, 0xdd, 0xeb, 0xbb, 0xf2, 0x55, 0xf4, 0xfd, 0xe7, 0x28, 0x98, 0xec, 0x1e, 0x2d, 0xe3,
	0xf0, 0x78, 0x19, 0x87, 0x7f, 0x96, 0x71, 0xf8, 0x6d, 0x15, 0x07, 0xc7, 0xab, 0x38, 0xf8, 0xb5,
	0x8a, 0x83, 0xf7, 0xd9, 0x3f, 0xd3, 0x82, 0xd8, 0xbe, 0x7c, 0xa2, 0x5f, 0xfa, 0x23, 0xf5, 0xa3,
	0x4f, 0x07, 0xfe, 0xe2, 0x9e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x61, 0x88, 0xed, 0x07, 0xd0,
	0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IcaConnectionId) > 0 {
		i -= len(m.IcaConnectionId)
		copy(dAtA[i:], m.IcaConnectionId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.IcaConnectionId)))
		i--
		dAtA[i] = 0x52
	}
	if m.LiquidityBootstrapped {
		i--
		if m.LiquidityBootstrapped {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.LiquidityBootstrapping {
		i--
		if m.LiquidityBootstrapping {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.Discount.Size()
		i -= size
		if _, err := m.Discount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.InitLiquidityPrice.Size()
		i -= size
		if _, err := m.InitLiquidityPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.DepositEndTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DepositEndTime))
		i--
		dAtA[i] = 0x28
	}
	if m.VestingDuration != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VestingDuration))
		i--
		dAtA[i] = 0x20
	}
	if len(m.AllocationToken) > 0 {
		i -= len(m.AllocationToken)
		copy(dAtA[i:], m.AllocationToken)
		i = encodeVarintParams(dAtA, i, uint64(len(m.AllocationToken)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DepositToken) > 0 {
		i -= len(m.DepositToken)
		copy(dAtA[i:], m.DepositToken)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DepositToken)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Maintainer) > 0 {
		i -= len(m.Maintainer)
		copy(dAtA[i:], m.Maintainer)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Maintainer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Maintainer)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DepositToken)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.AllocationToken)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.VestingDuration != 0 {
		n += 1 + sovParams(uint64(m.VestingDuration))
	}
	if m.DepositEndTime != 0 {
		n += 1 + sovParams(uint64(m.DepositEndTime))
	}
	l = m.InitLiquidityPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Discount.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.LiquidityBootstrapping {
		n += 2
	}
	if m.LiquidityBootstrapped {
		n += 2
	}
	l = len(m.IcaConnectionId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maintainer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Maintainer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocationToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllocationToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingDuration", wireType)
			}
			m.VestingDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositEndTime", wireType)
			}
			m.DepositEndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositEndTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitLiquidityPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitLiquidityPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Discount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Discount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityBootstrapping", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LiquidityBootstrapping = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityBootstrapped", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LiquidityBootstrapped = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IcaConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IcaConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
